package org.olcbox.app.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal val OlcboxDarkColorScheme = darkColorScheme(
    primary = Color(0xFFFFB4AB),
    onPrimary = Color(0xFF561D1D),
    primaryContainer = Color(0xFF6F3A3A),
    onPrimaryContainer = Color(0xFFFFDAD6),
    inversePrimary = Color(0xFF904B49),
    secondary = Color(0xFFE7BDB8),
    onSecondary = Color(0xFF442927),
    secondaryContainer = Color(0xFF5D3F3D),
    onSecondaryContainer = Color(0xFFFFDAD6),
    tertiary = Color(0xFFE4C08F),
    onTertiary = Color(0xFF402D0B),
    tertiaryContainer = Color(0xFF5B421E),
    onTertiaryContainer = Color(0xFFFFDDB0),
    background = Color(0xFF12090A),
    onBackground = Color(0xFFF7DEDC),
    surface = Color(0xFF12090A),
    onSurface = Color(0xFFF7DEDC),
    surfaceVariant = Color(0xFF55413F),
    onSurfaceVariant = Color(0xFFD8C2BF),
    surfaceContainerLowest = Color(0xFF0B0506),
    surfaceContainerLow = Color(0xFF1C1011),
    surfaceContainer = Color(0xFF251718),
    surfaceContainerHigh = Color(0xFF302122),
    surfaceContainerHighest = Color(0xFF3C2B2C),
    inverseSurface = Color(0xFFF7DEDC),
    inverseOnSurface = Color(0xFF362F2E),
    outline = Color(0xFFA38C89),
    outlineVariant = Color(0xFF55413F),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6)
)

internal val OlcboxLightColorScheme = lightColorScheme(
    primary = Color(0xFF904B49),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDAD6),
    onPrimaryContainer = Color(0xFF3B0808),
    inversePrimary = Color(0xFFFFB4AB),
    secondary = Color(0xFF775653),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFDAD6),
    onSecondaryContainer = Color(0xFF2C1513),
    tertiary = Color(0xFF735A2C),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDDB0),
    onTertiaryContainer = Color(0xFF281800),
    background = Color(0xFFFFF8F7),
    onBackground = Color(0xFF231918),
    surface = Color(0xFFFFF8F7),
    onSurface = Color(0xFF231918),
    surfaceVariant = Color(0xFFF5DDDA),
    onSurfaceVariant = Color(0xFF534341),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFFF0EE),
    surfaceContainer = Color(0xFFFFE9E7),
    surfaceContainerHigh = Color(0xFFF9DEDB),
    surfaceContainerHighest = Color(0xFFF1D6D3),
    inverseSurface = Color(0xFF392E2D),
    inverseOnSurface = Color(0xFFFFEDEA),
    outline = Color(0xFF857370),
    outlineVariant = Color(0xFFD8C2BF),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002)
)
